services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=librarydb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=libraryAdmin'
    ports:
      - '3308:3306'
    volumes:
      - biblioteca-mysql-data:/var/lib/mysql

volumes:
  biblioteca-mysql-data:
